### ISSUE TITLE
Avalonia

### ISSUE THREAD

**Issue by jinyuttt** [Splitwirez/AvaloniaRibbon#15]
Upgrade Avalonia version？

**Comment by Splitwirez** [comment]
If you're suggesting upgrading AvaloniaRibbon to Avalonia 0.10.0, I'll be looking into that at some point once the first 0.10.0 stable release is available.

**Comment by jinyuttt** [comment]
If there are interface changes, you can keep the old version and update to 0.10 preview version

**Comment by jinyuttt** [comment]
update 0.10?

**Comment by HankG** [comment]
I have an updated version mostly working with 0.10. To get it working I had to change the AvaloniaProperty.Register method since the signature changed (the verification thing Ribbon uses seems to do more than just verify). The extra particular syntax on some of the getters wanted explicit casts for the enums as well. With all of that it's running but I have two problems in the demo app. First, the initial ribbon renders but it's all white. Toggling back and forth across ribbon tabs work fine though. I'm not sure if it's a problem with that validation method doing some magic or something else. Second, the larger gallery sizes never re-expand with window resize. They will stay at whatever their smallest sizes are left the rest of the time.  You can see my progress in this branch:

https://github.com/HankG/AvaloniaRibbon/tree/update-avalonia-10

**Comment by jinyuttt** [comment]
@HankG   thanks

**Comment by jinyuttt** [comment]
@HankG  Can you help me solve a problem? I want to combine with dock, but I can't use ribbon window.
wieslawsoltes/Dock #168
