### ISSUE TITLE
Property "Background" doesn't work for "RibbonGroupBox"

### ISSUE THREAD

**Issue by f0xeri** [Splitwirez/AvaloniaRibbon#17]
Foreground works well, but background doesn't work for RibbonGroupBox. Color is unchangeble.

**Comment by seljmov** [comment]
@f0xeri 
Hi! I looked through the source code and realized that this happens due to the absence of the Background="{TemplateBinding Background} " parameter in the panel in line 43 here - [Fluent Theme RibbonGroupBox](https://github.com/Splitwirez/AvaloniaRibbon/blob/a2077ec0df75fa6c656ac502672b0408ca0c9962/AvaloniaUI.Ribbon/Themes/Fluent/Controls/RibbonGroupBox.xaml#L43) or in line 44 here - [Default Theme RibbonGroupBox](https://github.com/Splitwirez/AvaloniaRibbon/blob/a2077ec0df75fa6c656ac502672b0408ca0c9962/AvaloniaUI.Ribbon/Themes/Default/Controls/RibbonGroupBox.xaml#L44). This is a develop-branch that supports Avalonia 10.0.

You can replace these lines:
- Fluent RibbonGroupBox - ```<Panel Background="{TemplateBinding Background}">```
- Default RibbonGroupBox - ```<DockPanel Background="{TemplateBinding Background}">```

You'll get something like this: 
![image](https://user-images.githubusercontent.com/56289147/110290851-4cafae00-7ffc-11eb-8f64-da6cac234d72.png)

**Comment by f0xeri** [comment]
It works, thanks.

**Comment by Splitwirez** [comment]
I've just integrated a fix for this into the `develop` branch, which addresses this. Sorry for the inconvenience.

@f0xeri For future reference, could you please elaborate on your use case for this? It's always useful to know more about how people are using AvaloniaRibbon and how they would like to be able to use it, so that I can plan accordingly and better serve those needs.

**Comment by seljmov** [comment]
Not at all, @Splitwirez, thank you for the project) I actively use AvaloniaUI in my project and am happy to help it with development)
